### ISSUE TITLE
Z3 exception when using PRED_BOOL together with BW_BIN_ITP

### ISSUE THREAD

**Issue by leventeBajczi** [ftsrg/theta#117]
The following exception is encountered after the 5th iteration of the analysis on the below CFA:
`Sort mismatch at argument #1 for function (declare-fun or (Bool Bool) Bool) supplied sort is Int`

By changing any of the options (to for example PRED_CART or SEQ_ITP) the analysis either succeeds or times out after a long wait, but the exception above is not produced.

The entire config:
``` java
new CfaConfigBuilder(CfaConfigBuilder.Domain.PRED_BOOL, CfaConfigBuilder.Refinement.BW_BIN_ITP, Z3SolverFactory.getInstance())
					.precGranularity(CfaConfigBuilder.PrecGranularity.GLOBAL).search(CfaConfigBuilder.Search.ERR)
					.predSplit(CfaConfigBuilder.PredSplit.WHOLE).encoding(CfaConfigBuilder.Encoding.LBE).maxEnum(10).initPrec(CfaConfigBuilder.InitPrec.EMPTY)
					.pruneStrategy(PruneStrategy.LAZY).logger(new ConsoleLogger(Logger.Level.SUBSTEP))
```
The input CFA (note the lack of an `or` statement, which the exception would imply):
[cdaudio_simpl1.cil-1.cfa.txt](https://github.com/ftsrg/theta/files/6598168/cdaudio_simpl1.cil-1.cfa.txt)

**Comment by hajduakos** [comment]
I'm trying to reproduce the issue, but I have problems parsing the CFA, there are some variables defined multiple times, e.g., `stub_driver_init_ret4949`, `Irp393`, ... Are you sure you provided the right CFA?

**Comment by leventeBajczi** [comment]
Oh, then that was actually a bug in the frontend, as some variables appeared multiple times in the generated CFA. The in-memory CFA does not care about multiple variables with the same name and therefore no error was produced, but parsing back the CFA from its textual representation apparently (and rightfully) does. I reckon the exception above is also related to this issue, and therefore I am closing it. However, a check might be necessary in the CFA builder class to forbid non-uniquely named variables to prevent such problems in the future - would this be a good idea to implement?

**Comment by hajduakos** [comment]
Yes, good idea indeed. Not only variables, but locations should also have unique names. See #120
