### ISSUE TITLE
Update documentation for the floating point type, expressions and elements of the DSL

### ISSUE THREAD

**Issue by leventeBajczi** [ftsrg/theta#124]
- [ ] Create a summary on floating point support in Theta akin to [bitvectors.md](https://github.com/ftsrg/theta/blob/master/subprojects/cfa/cfa/doc/bitvectors.md)
- [x] Update the description of the CFA formalism in [README.md](https://github.com/ftsrg/theta/blob/master/subprojects/cfa/cfa/README.md)
- [ ] Add some example CFAs to showcase the new expressions (also suitable for testing purposes)

**Comment by hajduakos** [comment]
I think point number one is optional. It is nice to have a long and detailed description if you have time, but the important thing is to update the CFA formalism readme (point 2). You might just list the available operators/expressions there.

**Comment by leventeBajczi** [comment]
Please see PR #127, I think I covered all important aspects for point 2.
