### ISSUE TITLE
Fix missing library on Windows

### ISSUE THREAD

**Issue by hajduakos** [ftsrg/theta#131]
Currently, Windows build fails due to
```
java.lang.UnsatisfiedLinkError at Z3SolverFPTest.java:45
```

Probably one of the newly added libraries (related to floats) is missing.

**Comment by hajduakos** [comment]
**Update:** as of 83b9d4b, the tests are skipped so at least we can now build on Windows. However, as soon as someone tries to use floats, we will get an `UnsatisfiedLinkError`. It would be more user friendly to check for the OS and report a better message, like `OsNotSupportedException("Floats are not supported on Windows")` or something like that. Furthermore, the best would be of course if we could port the library to windows.

Removed the bug label and added enhancement instead.

**Comment by hajduakos** [comment]
#132 will fix this

**Comment by leventeBajczi** [comment]
#132 merged.
