### ISSUE TITLE
Add AZs thesis

### ISSUE THREAD

**Issue by hajduakos** [ftsrg/theta#152]
Please add your thesis to the publications, see instructions in readme here: https://github.com/ftsrg/theta/tree/gh-pages/publications

**Comment by AdamZsofi** [comment]
Done, added in [2939ad4](https://github.com/ftsrg/theta/commit/2939ad497c0b31fc5401418f3986a96ab15a266c) and [47e75ba](https://github.com/ftsrg/theta/commit/47e75ba867810a122fe8845e0c35c4f1721090f3).

**Comment by hajduakos** [comment]
Thanks
