### ISSUE TITLE
Suggestion: Add front-end for Constrained Horn Clauses

### ISSUE THREAD

**Issue by blishko** [ftsrg/theta#166]
As discussed at TACAS, it would be great if Theta could support CHC front-end. The language is a simple extension of SMT-LIB, format described [here](https://chc-comp.github.io/format.html).
At least transition systems (1 uninterpreted predicate and 3 clauses) and linear systems of CHCs (at most 1 uninterpreted predicate in the body of every clause) should directly map to STS and CFA in Theta's representation, I believe.

Then Theta could participate in [CHC-COMP](https://chc-comp.github.io), which would be great for the CHC community.

**Comment by hajduakos** [comment]
Thanks @blishko for the discussion and the suggestion! I've posted this in the Theta team Slack, hopefully someone can start working on this soon.
