### ISSUE TITLE
Wrong result is given for the unreach-call property

### ISSUE THREAD

**Issue by leventeBajczi** [ftsrg/theta#209]
Config 1: `--strategy DIRECT --maxenum 1 --loglevel RESULT --refinement SEQ_ITP --lbe LBE_SEQ --search ERR --prunestrategy FULL --predsplit ATOMS --cex-monitor DISABLE --domain EXPL`
Problem17_label11.yml

Config 2: `--strategy DIRECT --maxenum 1 --loglevel RESULT --refinement SEQ_ITP --lbe LBE_SEQ --search ERR --prunestrategy FULL --predsplit ATOMS --cex-monitor DISABLE --domain PRED_CART`
Problem10_label30.yml, Problem11_label40.yml, Problem15_label49.yml

**Comment by s0mark** [comment]
I fixed the integer division and modulo problems in #230. I ran Theta with the configurations and the tasks mentioned in the issue, it no longer gives wrong answers to them.

This issue brings up the possibility of further discrepancies between the semantics of C, Theta and the solvers: the `sdiv`/`srem` and `udiv`/`urem` operators for bitvectors might also be effected.

**Comment by leventeBajczi** [comment]
Thanks! Closing.
