### ISSUE TITLE
Progress Check

### ISSUE THREAD

**Issue by leventeBajczi** [ftsrg/theta#219]
argnode equality (consult @leventeBajczi or @AdamZsofi)

**Comment by leventeBajczi** [comment]
Is this fully done? Has the ARG node equality check been solved (@csanadtelbisz , @AdamZsofi)?

**Comment by csanadtelbisz** [comment]
https://github.com/ftsrg/theta/blob/608428548b633398261fc40addc44f77b6741a2e/subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/algorithm/ArgNode.java#L292

**Comment by leventeBajczi** [comment]
van-e a checkben argnode equality check - vszeg nincs csak argnode - szülő számítson equalitynél, gyerekei ne, hashelve legyen és az gyerekek kifejtésével ne változzon, cover élek ne számítsanak ebben sehol

**Comment by leventeBajczi** [comment]
szülő érdekel, belejövő él a szülőből érdekel, node maga érdekel, kimenő él nem érdekel, covered by semmilyen iránya nem érdekel

**Comment by leventeBajczi** [comment]
we need to fix equals - compare that way and in progress check it will be enough to check leaf? Depends - need to talk about it a bit more

**Comment by leventeBajczi** [comment]
Fixed in #238 .
