### ISSUE TITLE
Cfa DSL bad parsing around 'x+1' vs 'x + 1' in expression

### ISSUE THREAD

**Issue by radl97** [ftsrg/theta#47]
In a CFA expression, 'x+1' has bad parsing, because '+1' is parsed first in INT as a token:
https://github.com/ftsrg/theta/blob/master/subprojects/cfa/src/main/antlr/CfaDsl.g4#L387

It does not have the same behaviour, if it has a space between '+' and '1'.

If we have to process everything the same way, I've found 2 solutions (untested):

Here at additiveExpr:
https://github.com/ftsrg/theta/blob/master/subprojects/cfa/src/main/antlr/CfaDsl.g4#L183

If we write 

```(firstOper=(PLUS|MINUS))? ops+=multiplicativeExpr (opers+=(PLUS | MINUS) ops+=multiplicativeExpr)*```

The parsing should be OK, but now there is a special case where there is a sign before the first token.

Another solution would be modifying at negExpr:
https://github.com/ftsrg/theta/blob/master/subprojects/cfa/src/main/antlr/CfaDsl.g4#L192

There could be a `PLUS op=negExpr` which does not negate the value, but only consumes the unneeded plus sign.

**Comment by hajduakos** [comment]
@as3810t any thoughts on this?

**Comment by radl97** [comment]
I think `+1` shoul

**Comment by radl97** [comment]
(sorry, misclick :/ )
As I understand:
+1 should not be understood as a token.
`a := +1` should be good, but not with `+1` as a token. It should be + as a prefix operator.
So basically tokenization should not include the signs.
+1 should be simplified as 1.

**Comment by as3810t** [comment]
In C-like programming languages there is usually both a unary- and a unary+ operator. The unary+ usually does not do anything (but for instance in C++ it can be overridden :D ).

Thereby I think the proper solution would be to introduce `IntPosExpr`, `RatPosExpr` and `BvPosExpr` which correspond to the unary plus operator. These (as of now) would be totally transparent, but maybe they could be a big help later on.

**Comment by hajduakos** [comment]
Okay, Iike the idea. @as3810t if you have some time can you please do it? This is a low priority task, not urgent.
