### ISSUE TITLE
Log counterexaple to file rather than stdout

### ISSUE THREAD

**Issue by as3810t** [ftsrg/theta#48]
Currently theta-cfa-cli tool has a command line option --cex. When present, the tool logs the counterexample (if found) to the standard output.

Consider supporting writing the counterexample to a file instead, as it would enhance theta's interoperability with other tools, that require the counterexample. This would allow to change the output independently from the format of the counterexample, and it would lead to a cleaner, simpler user interface.

**Comment by hajduakos** [comment]
Fixed in 0a5d3d1, `--cex` now accepts a file name as string. On Windows, the old behavior (writing to console) can be achieved by providing `--cex CON`. I haven't tested it but I assume on Linux it would be `--cex /dev/stdout`.

@as3810t please check if it works for you and close the issue if yes.

**Comment by as3810t** [comment]
Works like a charm! 
On linux `--cex /dev/stdout` works as well.
Thank you!
