### ISSUE TITLE
ExprWriter does not support bitvectors and array literals

### ISSUE THREAD

**Issue by as3810t** [ftsrg/theta#67]
The DispatchTable in ExprWriter lacks the entries for handling bitvectors and array literals

**Comment by hajduakos** [comment]
True. The main idea that the `toString` of the expressions gives a Lisp-style output that can easily be parsed. In contrast, the `ExprWriter` utility class is meant to produce human readable output (similar to the Antlr DSLs). As far as I see the PR will resolve this issue, I will merge soon.
