### ISSUE TITLE
Extract cli commons

### ISSUE THREAD

**Issue by radl97** [ftsrg/theta#80]
Some exception handling-related and output formatting (benchmark table) could be extracted to a subproject so cli interfaces need not be synchronized among versions.

Maybe there is not enough thing to extract, maybe some reflection magic is needed...

**Comment by hajduakos** [comment]
Agreed. There are common stuff. I will check and see if we can go this direction.

**Comment by hajduakos** [comment]
I'd say it's more like an (internal) enhancement than a feature request so I adjusted the labels
