### ISSUE TITLE
Unchecked/unsafe operation warnings related to statements

### ISSUE THREAD

**Issue by hajduakos** [ftsrg/theta#86]
Building Theta gives two warnings related to `StmtToExprTransformer` and `StmtApplier`:
```
> Task :theta-core:compileJava
Note: theta\subprojects\core\src\main\java\hu\bme\mit\theta\core\utils\StmtToExprTransformer.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

```
> Task :theta-analysis:compileJava
Note: theta\subprojects\analysis\src\main\java\hu\bme\mit\theta\analysis\expl\StmtApplier.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

As far as I see, we have this since the new statements (related to XSTS) were introduced.

**Comment by mondokm** [comment]
I fixed this on the `xsts-dev` branch, but found that `theta\cfa\analysis\CfaTest.java` also has this warning

**Comment by hajduakos** [comment]
Great, thanks! If you know the solution, feel free to also fix CfaTest.
