### ISSUE TITLE
Give warnings if solver does not support some feature in the model/algorithm

### ISSUE THREAD

**Issue by hajduakos** [ftsrg/theta#90]
It would be nice to give a warning (with `Level.RESULT`) if the CFA contains bitvectors, but the refinement might not support it (e.g.,`SEQ_ITP`).

**Comment by as3810t** [comment]
I agree. The question is where this functionality should be implemented in the code.

My argument is, that the interchangeable solver backend coming with the changes in branch solver-smtlib, the number of such incompatibilities will increase. For example:

- Z3 does not support interpolation with bitvectors (in all circumstences)
- CVC4 does not support Theta's function typ
- MathSAT does not support tree interpolation (while Z3 and SMTInterpol does)
- SMTInterpol does not support interpolation with bitvectors, rationals, ...
- etc...

I think it would be beneficial to implement a general interface for solvers to describe the functionality they support, and than algorithms, formalisms could assert that.

**Comment by hajduakos** [comment]
True, I agree. I think we can never be complete in this sense, i.e., there will always be cases where an exception occurs in the middle of the algorithm). However, if we can at least detect the major cases that would be nice. I like this idea of letting solvers describe their capabilities via an interface. Let's discuss this in more detail on our next meeting.
