### ISSUE TITLE
Build fails on archlinux

### ISSUE THREAD

**Issue by mchalupa** [ftsrg/theta#95]
Hi,

when I try to build theta I get the following error:

```
$ gradle build

Welcome to Gradle 6.6.1!

Here are the highlights of this release:
 - Experimental build configuration caching
 - Built-in conventions for handling credentials
 - Java compilation supports --release flag

For more details see https://docs.gradle.org/6.6.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :buildSrc:compileKotlin
w: /home/marek/src/theta/buildSrc/src/main/kotlin/tool-common.gradle.kts: (22, 48): 'getter for version: String?' is deprecated. Deprecated in Java

> Configure project :
e: /home/marek/src/theta/build.gradle.kts:37:9: Val cannot be reassigned
e: /home/marek/src/theta/build.gradle.kts:38:9: Val cannot be reassigned
e: /home/marek/src/theta/build.gradle.kts:42:9: Val cannot be reassigned
e: /home/marek/src/theta/build.gradle.kts:45:29: Type mismatch: inferred type is FileCollection! but ConfigurableFileCollection! was expected

FAILURE: Build failed with an exception.

* Where:
Build file '/home/marek/src/theta/build.gradle.kts' line: 37

* What went wrong:
Script compilation errors:

  Line 37:         sourceDirectories = files(reportTasks.map { it.allSourceDirs })
                   ^ Val cannot be reassigned

  Line 38:         classDirectories = files(reportTasks.map { it.allClassDirs })
                   ^ Val cannot be reassigned

  Line 42:         executionData = allExecutionData
                   ^ Val cannot be reassigned

  Line 45:             executionData = allExecutionData.filter { it.exists() }
                                       ^ Type mismatch: inferred type is FileCollection! but ConfigurableFileCollection! was expected

4 errors

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2m 23s
```
I did not find any guidelines on how to build the project. Sorry about filing this issue if the problem is on my side.

**Comment by radl97** [comment]
I'm running 5RC without problems.

It seems to be a feature of Gradle 5. The workaround(/fix?) is to use setExecutionData instead of executionData (taken from https://github.com/gradle/kotlin-dsl-samples/issues/1265 )
I'll look into this

**Comment by radl97** [comment]
I've reproduced the bug, it really is the new Gradle version. The PR linked does not work well... :/ 

@mchalupa In the meantime, using `./gradlew build` works fine (as it uses a fixed version of Gradle, I think?). 

Oh, and I also use arch btw.

**Comment by hajduakos** [comment]
Hi @mchalupa! As @radl97 pointed out, it seems like you are using `gradle build`, which runs the globally installed Gradle from your system, which seems to be version 6.6.1. Theta currently relies on Gradle 5.0, and has some features that are incompatible with 6.x. If you run `./gradlew build` from the root of the repo, it should run the local Gradle (5.0) that is automatically downloaded into the repo. You can find more instructions in [doc/Build.md](https://github.com/ftsrg/theta/blob/master/doc/Build.md). If you would like to use some concrete tool, e.g., [cfa-cli](https://github.com/ftsrg/theta/tree/master/subprojects/cfa-cli) then these projects also have instructions in their readme.

Let us know if `./gradlew build` works, then we can close this issue.

**Comment by hajduakos** [comment]
In the meantime we upgraded to Gradle 6.1 as well (see #97), so `gradle build` should also work in your case. Nevertheless, I still recommend using `./gradlew build`.

**Comment by radl97** [comment]
Minor correction: it's 6.6.1, not 6.1 :)
(Shadow (fat-jar generating package) version was the one upgraded to 6.1)

**Comment by mchalupa** [comment]
Both `gradle build` and `./gradlew build` work now, thanks!
