### ISSUE TITLE
Upgrade to Gradle 6.x

### ISSUE THREAD

**Issue by hajduakos** [ftsrg/theta#97]
We still use Gradle 5.0, which is from 2018, so we should upgrade to a more recent version. There are some incompatibilities that need to be fixed. (See #95)

**Comment by radl97** [comment]
- Update gradle wrapper to a more recent version
- Fix bug (Already done in #96 )
- There is another related error when building with Gradle 6.6.1, where a jacoco file does not get written to...

**Comment by radl97** [comment]
@hajduakos Can you take a look at this?

> Unable to read execution data file /home/runner/work/theta/theta/subprojects/cfa-cli/build/jacoco/test.exec

taken from the build output: https://github.com/ftsrg/theta/pull/96/checks?check_run_id=1309038003
